# Generated by Django 2.0.7 on 2019-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lti_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('iki_user_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
