# Generated by Django 2.0.7 on 2019-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sis_user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='lti_id',
            field=models.IntegerField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
