# Generated by Django 2.0.7 on 2019-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iki', '0002_auto_20190315_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iki_user_id',
            field=models.IntegerField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
