# Generated by Django 2.0.7 on 2019-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iki', '0003_auto_20190315_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lti_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
