# Generated by Django 2.0.7 on 2019-03-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_app_lti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLTICourse',
            fields=[
                ('lticourse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app_lti.LTICourse')),
                ('canvas_course_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('django_app_lti.lticourse',),
        ),
        migrations.CreateModel(
            name='MyLTICourseUser',
            fields=[
                ('lticourseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app_lti.LTICourseUser')),
                ('user_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('django_app_lti.lticourseuser',),
        ),
        migrations.CreateModel(
            name='MyLTIResource',
            fields=[
                ('ltiresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app_lti.LTIResource')),
            ],
            bases=('django_app_lti.ltiresource',),
        ),
    ]
